export const DEFAULT_ALERT_GROUPS = [
    {
        id: 'academico',
        label: 'Academico',
        barClass: 'bg-sky-50 text-sky-500',
        iconClass: 'bg-sky-50 text-sky-500 border-sky-200',
        items: [
            {
                id: 'novos-pedidos-inscricao',
                title: 'Novos Pedidos de Inscricao',
                description: 'Quando um novo aluno solicita inscricao',
                icon: 'UserPlus',
                appEnabled: true,
                emailEnabled: true,
                smsEnabled: false,
            },
            {
                id: 'ausencias-alunos',
                title: 'Ausencias de Alunos',
                description: 'Quando um aluno falta a uma sessao agendada',
                icon: 'GraduationCap',
                appEnabled: true,
                emailEnabled: false,
                smsEnabled: true,
            },
            {
                id: 'ausencias-professores',
                title: 'Ausencias de Professores',
                description: 'Quando um professor reporta uma ausencia',
                icon: 'UserRoundX',
                appEnabled: true,
                emailEnabled: true,
                smsEnabled: false,
            },
            {
                id: 'renovacao-matricula',
                title: 'Renovacao de Matricula',
                description: 'Quando a matricula do aluno e renovada.',
                icon: 'RefreshCcw',
                appEnabled: true,
                emailEnabled: true,
                smsEnabled: false,
            },
        ],
    },
    {
        id: 'operacional',
        label: 'Operacional',
        barClass: 'bg-emerald-50 text-emerald-600',
        iconClass: 'bg-emerald-50 text-emerald-600 border-emerald-200',
        items: [
            {
                id: 'sessoes-agendadas',
                title: 'Sessoes Agendadas',
                description: 'Resumo diario das sessoes do dia seguinte',
                icon: 'CalendarCheck2',
                appEnabled: true,
                emailEnabled: true,
                smsEnabled: false,
            },
        ],
    },
    {
        id: 'sistema',
        label: 'Sistema',
        barClass: 'bg-violet-50 text-violet-500',
        iconClass: 'bg-violet-50 text-violet-500 border-violet-200',
        items: [
            {
                id: 'atualizacoes-sistema',
                title: 'Atualizacoes do Sistema',
                description: 'Notificacao sobre novas funcionalidades',
                icon: 'MonitorCog',
                appEnabled: true,
                emailEnabled: true,
                smsEnabled: false,
            },
            {
                id: 'backups-automaticos',
                title: 'Backups Automaticos',
                description: 'Confirmacao de backups realizados com sucesso',
                icon: 'Bell',
                appEnabled: false,
                emailEnabled: false,
                smsEnabled: false,
            },
            {
                id: 'atividade-suspeita',
                title: 'Atividade Suspeita',
                description: 'Tentativas de acesso nao autorizado',
                icon: 'KeyRound',
                appEnabled: true,
                emailEnabled: true,
                smsEnabled: true,
            },
            {
                id: 'criacao-conta',
                title: 'Criacao de Conta',
                description: 'Quando uma nova conta de professor ou aluno e criada',
                icon: 'UserPlus',
                appEnabled: true,
                emailEnabled: false,
                smsEnabled: false,
            },
            {
                id: 'limpeza-dados-massa',
                title: 'Limpeza de Dados em Massa',
                description: 'Quando e executada uma limpeza de dados em massa',
                icon: 'Trash2',
                appEnabled: true,
                emailEnabled: true,
                smsEnabled: false,
            },
            {
                id: 'aluno-eliminado',
                title: 'Aluno Eliminado',
                description: 'Quando um aluno e eliminado definitivamente do sistema',
                icon: 'UserMinus',
                appEnabled: true,
                emailEnabled: true,
                smsEnabled: false,
            },
        ],
    },
];

export const CUSTOM_GROUP_TEMPLATE = {
    id: 'personalizados',
    label: 'Personalizados',
    barClass: 'bg-amber-50 text-amber-600',
    iconClass: 'bg-amber-50 text-amber-600 border-amber-200',
    items: [],
};
